<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FoodSeeder extends Seeder
{
    public function run()
    {
        DB::table('foods')->insert([
            [
                'category_id' => 1,
                'name' => 'Edamame',
                'jpName' => '枝豆',
                'price' => 580,
                'description' => 'Đậu nành Nhật Bản hấp với muối biển',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Agedashi Tofu',
                'jpName' => '揚げ出し豆腐',
                'price' => 680,
                'description' => 'Đậu phụ chiên giòn phục vụ với nước tương dashi và hành lá',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Gyoza',
                'jpName' => '餃子',
                'price' => 750,
                'description' => 'Bánh xếp Nhật Bản nhân thịt lợn và rau, chiên giòn đáy',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Takoyaki',
                'jpName' => 'たこ焼き',
                'price' => 780,
                'description' => 'Bánh bạch tuộc kiểu Osaka với sốt takoyaki, mayonnaise và bông cá ngừ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Miso Soup',
                'jpName' => '味噌汁',
                'price' => 480,
                'description' => 'Súp miso truyền thống với đậu phụ, rong biển và hành lá',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Seaweed Salad',
                'jpName' => '海藻サラダ',
                'price' => 680,
                'description' => 'Salad rong biển tươi với dầu mè',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Sake & Đồ uống có cồn (category_id = 2)
            [
                'category_id' => 2,
                'name' => 'Junmai Daiginjo',
                'jpName' => null,
                'price' => 980,
                'description' => 'Sake Junmai Daiginjo - giá cho 1 ly',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Ginjo',
                'jpName' => null,
                'price' => 780,
                'description' => 'Sake Ginjo - giá cho 1 ly',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Honjozo',
                'jpName' => null,
                'price' => 680,
                'description' => 'Sake Honjozo - giá cho 1 ly',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Nigori (Sake đục)',
                'jpName' => null,
                'price' => 780,
                'description' => 'Sake Nigori (đục) - giá cho 1 ly',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Sake nóng',
                'jpName' => null,
                'price' => 680,
                'description' => 'Sake nóng - giá cho 1 ly',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Beer & Alcohol (category_id = 2)
            [
                'category_id' => 2,
                'name' => 'Asahi Super Dry',
                'jpName' => null,
                'price' => 680,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Sapporo Premium',
                'jpName' => null,
                'price' => 680,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Kirin Ichiban',
                'jpName' => null,
                'price' => 680,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Suntory Whisky',
                'jpName' => null,
                'price' => 880,
                'description' => 'Giá cho 1 ly',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Plum Wine (Umeshu)',
                'jpName' => null,
                'price' => 780,
                'description' => 'Giá cho 1 ly',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Shochu',
                'jpName' => null,
                'price' => 780,
                'description' => 'Giá cho 1 ly',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Non Alcoholic (category_id = 2)
            [
                'category_id' => 2,
                'name' => 'Trà xanh Nhật Bản',
                'jpName' => null,
                'price' => 480,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Trà Genmaicha',
                'jpName' => null,
                'price' => 480,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Trà Hojicha',
                'jpName' => null,
                'price' => 480,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Ramune (Soda Nhật)',
                'jpName' => null,
                'price' => 580,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Nước ép trái cây tươi',
                'jpName' => null,
                'price' => 680,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Nước lọc Evian',
                'jpName' => null,
                'price' => 380,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Tekka Don',
                'jpName' => '鉄火丼',
                'price' => 1680,
                'description' => 'Cơm phủ cá ngừ sashimi',
                'image' => 'https://i.pinimg.com/736x/33/79/fb/3379fb928fa3b06997addd2c7941202a.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Salmon Don',
                'jpName' => 'サーモン丼',
                'price' => 1580,
                'description' => 'Cơm phủ cá hồi sashimi',
                'image' => 'https://i.pinimg.com/736x/33/79/fb/3379fb928fa3b06997addd2c7941202a.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Unagi Don',
                'jpName' => '鰻丼',
                'price' => 2280,
                'description' => 'Cơm phủ lươn nướng sốt teriyaki',
                'image' => 'https://i.pinimg.com/736x/33/79/fb/3379fb928fa3b06997addd2c7941202a.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Chirashi Don',
                'jpName' => 'ちらし丼',
                'price' => 2480,
                'description' => 'Cơm phủ nhiều loại sashimi và trứng cá',
                'image' => 'https://i.pinimg.com/736x/33/79/fb/3379fb928fa3b06997addd2c7941202a.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Tempura Udon',
                'jpName' => '天ぷらうどん',
                'price' => 1380,
                'description' => 'Mì udon nóng với tempura tôm và rau củ',
                'image' => 'https://i.pinimg.com/736x/33/79/fb/3379fb928fa3b06997addd2c7941202a.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Zaru Soba',
                'jpName' => 'ざるそば',
                'price' => 1180,
                'description' => 'Mì soba lạnh với nước chấm',
                'image' => 'https://i.pinimg.com/736x/33/79/fb/3379fb928fa3b06997addd2c7941202a.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Nabeyaki Udon',
                'jpName' => '鍋焼きうどん',
                'price' => 1580,
                'description' => 'Mì udon nóng trong nồi với trứng, tempura và các loại hải sản',
                'image' => 'https://i.pinimg.com/736x/33/79/fb/3379fb928fa3b06997addd2c7941202a.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Yakisoba',
                'jpName' => '焼きそば',
                'price' => 1280,
                'description' => 'Mì xào với thịt và rau củ',
                'image' => 'https://i.pinimg.com/736x/33/79/fb/3379fb928fa3b06997addd2c7941202a.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 4,
                'name' => 'California Roll',
                'jpName' => 'カリフォルニアロール',
                'price' => 850,
                'description' => 'Cơm cuộn với bơ, dưa leo, cua giả và sốt mayonnaise',
                'image' => '/images/rolls/california.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 4,
                'name' => 'Dragon Roll',
                'jpName' => 'ドラゴンロール',
                'price' => 1200,
                'description' => 'Cuộn cá ngừ, dưa leo, phủ cá hồi và sốt cay đặc biệt',
                'image' => '/images/rolls/dragon.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 4,
                'name' => 'Spicy Tuna Roll',
                'jpName' => 'スパイシーツナロール',
                'price' => 900,
                'description' => 'Cơm cuộn cá ngừ cay cùng sốt đặc trưng và hành lá',
                'image' => '/images/rolls/spicy-tuna.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 4,
                'name' => 'Philadelphia Roll',
                'jpName' => 'フィラデルフィアロール',
                'price' => 950,
                'description' => 'Cơm cuộn cá hồi hun khói, phô mai kem và dưa leo',
                'image' => '/images/rolls/philadelphia.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 4,
                'name' => 'Rainbow Roll',
                'jpName' => 'レインボーロール',
                'price' => 1300,
                'description' => 'Cuộn cá ngừ, cá hồi, cá trắng, bơ và dưa leo phủ nhiều loại cá khác nhau',
                'image' => '/images/rolls/rainbow.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 5,
                'name' => 'Maguro (Cá ngừ)',
                'jpName' => '鮪',
                'price' => 1280,
                'description' => '5 miếng',
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 5,
                'name' => 'Sake (Cá hồi)',
                'jpName' => '鮭',
                'price' => 1180,
                'description' => '5 miếng',
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 5,
                'name' => 'Hamachi (Cá buri)',
                'jpName' => 'はまち',
                'price' => 1280,
                'description' => '5 miếng',
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 5,
                'name' => 'Tai (Cá tráp đỏ)',
                'jpName' => '鯛',
                'price' => 1380,
                'description' => '5 miếng',
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 5,
                'name' => 'Hotate (Sò điệp)',
                'jpName' => '帆立',
                'price' => 1480,
                'description' => '5 miếng',
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 5,
                'name' => 'Amaebi (Tôm ngọt)',
                'jpName' => '甘海老',
                'price' => 1580,
                'description' => '5 miếng',
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 5,
                'name' => 'Moriawase Nhỏ',
                'jpName' => '刺身盛り合わせ小',
                'price' => 2800,
                'description' => 'Bộ sưu tập 3 loại cá (12 miếng)',
                'image' => 'https://i.pinimg.com/736x/f7/c8/38/f7c83832cb63a737e33df7552a5ec5a6.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 5,
                'name' => 'Moriawase Vừa',
                'jpName' => '刺身盛り合わせ中',
                'price' => 4200,
                'description' => 'Bộ sưu tập 5 loại cá (20 miếng)',
                'image' => 'https://i.pinimg.com/736x/99/a5/88/99a588d49d24d58ac9f0a3a4531146bb.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 5,
                'name' => 'Moriawase Lớn',
                'jpName' => '刺身盛り合わせ大',
                'price' => 6800,
                'description' => 'Bộ sưu tập 7 loại cá (30 miếng)',
                'image' => 'https://i.pinimg.com/736x/64/77/c2/6477c29df6d33f09ffb5bb21a916d1c0.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 5,
                'name' => 'Sashimi Đặc biệt',
                'jpName' => '特上刺身',
                'price' => 8800,
                'description' => 'Bộ sưu tập cao cấp với các loại cá hiếm (25 miếng)',
                'image' => 'https://i.pinimg.com/736x/be/d8/6f/bed86fc74d63d840f49ecf035f713ea6.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 6,
                'name' => 'Maguro (Cá ngừ)',
                'jpName' => '鮪',
                'price' => 780,
                'description' => null,
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 6,
                'name' => 'Sake (Cá hồi)',
                'jpName' => '鮭',
                'price' => 720,
                'description' => null,
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 6,
                'name' => 'Ebi (Tôm)',
                'jpName' => '海老',
                'price' => 680,
                'description' => null,
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 6,
                'name' => 'Tamago (Trứng)',
                'jpName' => '玉子',
                'price' => 580,
                'description' => null,
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 6,
                'name' => 'Ika (Mực)',
                'jpName' => '烏賊',
                'price' => 680,
                'description' => null,
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 6,
                'name' => 'Unagi (Lươn)',
                'jpName' => '鰻',
                'price' => 880,
                'description' => null,
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Premium Nigiri
            [
                'category_id' => 6,
                'name' => 'Otoro (Bụng cá ngừ)',
                'jpName' => '大トロ',
                'price' => 1280,
                'description' => null,
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 6,
                'name' => 'Uni (Cầu gai)',
                'jpName' => '雲丹',
                'price' => 1580,
                'description' => null,
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 6,
                'name' => 'Amaebi (Tôm ngọt)',
                'jpName' => '甘海老',
                'price' => 980,
                'description' => null,
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 6,
                'name' => 'Hotate (Sò điệp)',
                'jpName' => '帆立',
                'price' => 880,
                'description' => null,
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 6,
                'name' => 'Ikura (Trứng cá hồi)',
                'jpName' => 'いくら',
                'price' => 980,
                'description' => null,
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 6,
                'name' => 'Anago (Lươn biển)',
                'jpName' => '穴子',
                'price' => 980,
                'description' => null,
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Nigiri Sets
            [
                'category_id' => 6,
                'name' => 'Nigiri 6 miếng',
                'jpName' => '握り6貫',
                'price' => 2400,
                'description' => 'Lựa chọn của đầu bếp',
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 6,
                'name' => 'Nigiri 8 miếng',
                'jpName' => '握り8貫',
                'price' => 3200,
                'description' => 'Lựa chọn của đầu bếp',
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 6,
                'name' => 'Nigiri 10 miếng',
                'jpName' => '握り10貫',
                'price' => 4000,
                'description' => 'Lựa chọn của đầu bếp',
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 6,
                'name' => 'Nigiri 12 miếng',
                'jpName' => '握り12貫',
                'price' => 4800,
                'description' => 'Lựa chọn của đầu bếp',
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 6,
                'name' => 'Nigiri Đặc biệt',
                'jpName' => '特上握り',
                'price' => 5800,
                'description' => '8 miếng cao cấp',
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
